// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGgY4oqDvib8egJ8AXU5WIHEUlfzU49zQ',
    appId: '1:1056630945037:web:188a97c12c63392971ec44',
    messagingSenderId: '1056630945037',
    projectId: 'tbcareappmain',
    authDomain: 'tbcareappmain.firebaseapp.com',
    storageBucket: 'tbcareappmain.firebasestorage.app',
    measurementId: 'G-LXVPB3WZFM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0IUeeC0wKXSq2onXlgi2UwF_XLf4a7Bk',
    appId: '1:1056630945037:android:b3e6c11f9324c33771ec44',
    messagingSenderId: '1056630945037',
    projectId: 'tbcareappmain',
    storageBucket: 'tbcareappmain.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1rCwk7lApcEzPyqGbWynEygCtZ09C4TQ',
    appId: '1:1056630945037:ios:978224bf303c6d8c71ec44',
    messagingSenderId: '1056630945037',
    projectId: 'tbcareappmain',
    storageBucket: 'tbcareappmain.firebasestorage.app',
    iosBundleId: 'com.example.yourapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1rCwk7lApcEzPyqGbWynEygCtZ09C4TQ',
    appId: '1:1056630945037:ios:978224bf303c6d8c71ec44',
    messagingSenderId: '1056630945037',
    projectId: 'tbcareappmain',
    storageBucket: 'tbcareappmain.firebasestorage.app',
    iosBundleId: 'com.example.yourapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGgY4oqDvib8egJ8AXU5WIHEUlfzU49zQ',
    appId: '1:1056630945037:web:e4ce64ff3596a2cf71ec44',
    messagingSenderId: '1056630945037',
    projectId: 'tbcareappmain',
    authDomain: 'tbcareappmain.firebaseapp.com',
    storageBucket: 'tbcareappmain.firebasestorage.app',
    measurementId: 'G-C90BXWMB4X',
  );

}